site_name: Psychology Notes
site_url: https://psychology-notes.fly.dev/
repo_url: https://github.com/yetanotherchris/Psychology-Notes/
repo_name: yetanotherchris/Psychology-Notes/
docs_dir: docs

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - attr_list

nav:
  - Home: README.md
  - Tools:
    - Ask LLamas: ask-llamas.md
    - Academic Search: academic-search.md
    - Questionnaires: questionnaires-list.md
  - Cluster B:
    - Overview: Cluster-B/README.md
    - Cluster-B/narcissism-authors.md
    - Cluster-B/chatgpt-on-npd.md
    - Cluster-B/the-middle-years-book.md
    - Cluster-B/vaknin-narcissism-notes.md
    - Cluster-B/vaknin-references.md
  - authors.md
  - chatgpt-notes.md
  - cognitive-biases.md
  - emotions.md
  - logical-fallacies.md
  - Psychotherapy-Based Modalities: psychotherapy_modalities_rooted_list.md
  - stress.md
  - youtube-videos.md
  - experimentation-and-statistics.md

